on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PAGES_REPOSITORY: muhiro12/muhiro12.github.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout pages repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.PAGES_REPOSITORY }}
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          path: pages

      - name: Cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter

      - name: Flutter action
        uses: subosito/flutter-action@v1

      - name: Flutter build
        run: |
          flutter pub get
          flutter build web --base-href=/${{ github.event.repository.name }}/

      - name: Deploy to GitHub Pages
        run: |
          cd pages/
          cp -r ../build/web/. ${{ github.event.repository.name }}/
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git add .
          git commit -m '[${{ github.event.repository.name }}] ${{ github.event.commits[0].message }}'
          git push origin HEAD
