on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set ignored files
        run: echo ${{ secrets.ENV }} | base64 -d > production.env

      - name: Cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter

      - name: Flutter action
        uses: subosito/flutter-action@v1

      - name: Flutter build
        run: |
          flutter pub get
          flutter build web

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_AFTERGLOW_DIARIES }}'
          channelId: live
          projectId: the-afterglow-diaries
